# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  blazorsqlserver:
    image: blazorsqlserver
    build:
      context: .
      dockerfile: BlazorSQLServer/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5277:5277
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
