# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  api:
    image: productcatalog
    build:
      context: .
      dockerfile: ProductCatalog.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5164:5164
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    depends_on:
      - db
  db:
    container_name: mysqldb
    image: mysql:9.1.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=catalog
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=productsdb
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
