FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 5223

ENV ASPNETCORE_URLS=http://+:5223

USER app
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG configuration=Release
WORKDIR /src
COPY ["EFCoreDocker.API/EFCoreDocker.API.csproj", "EFCoreDocker.API/"]
RUN dotnet restore "EFCoreDocker.API/EFCoreDocker.API.csproj"
COPY . .
WORKDIR "/src/EFCoreDocker.API"
RUN dotnet build "EFCoreDocker.API.csproj" -c $configuration -o /app/build

FROM build AS publish
ARG configuration=Release
RUN dotnet publish "EFCoreDocker.API.csproj" -c $configuration -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "EFCoreDocker.API.dll"]
