services:
  db:
    image: 'mysql'
    volumes:
      - produtosdb:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.prod
    networks:
      - backend
    environment:
      - MYSQL_DATABASE=produtosdb
      - MYSQL_PASSWORD=secret
    ports:
      - 5001:8080
    depends_on:
      db:
        condition: service_healthy
volumes:
  produtosdb:
networks:
  backend:
