# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  catalog-db:
    image: mongo
  catalog-api:
    image: catalogapi:dev
    build:
      context: .
      dockerfile: Microservices.Catalog/Catalog.API/Dockerfile
      args:
        - configuration=Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
volumes:
  catalog_data:


